### ISSUE TITLE
Sprites

### ISSUE THREAD

**Issue by JojoFR1** [Aeyama-Mod/aeyama#108]
- [ ] Blocks
  - [ ] Large Stockpile
  - [ ] Brick Maker
  - [x] Shredder
  - [ ] Craker (RESPRITE)
  - [ ] Research Station
  - [ ] Ground Scanner
  - [x] Ore Smelter (RESPRITE)
    - [x] Iron Overlay
    - [x] Copper Overlay
    - [x] Zinc Overlay
  - [ ] Ore Foundry (RESPRITE)
    - [ ] Brass Overlay
    - [ ] Steel Overlay

- [ ] Items
  - [ ] Raw Tin
  - [ ] Tin
  - [ ] Bronze
  - [ ] Raw Aluminium
  - [ ] Aluminium
  - [ ] Raw Titanium
  - [ ] Titanium
  - [ ] Armor Plating

- [x] Liquids

- [X] Units

**Comment by Stieno3000** [comment]
can i maybe contribute with some sprites?

**Comment by Stieno3000** [comment]
> > can i maybe contribute with some sprites?
> 
> Yes you can, no problem

ok! can i just start on something or is there something i need to know? such as a color pallet or something?

**Comment by Stieno3000** [comment]
dont have discord, should i make a account real quick or do you have reddit or something we can talk on?

**Comment by FredyJabe** [comment]
> dont have discord, should i make a account real quick or do you have reddit or something we can talk on?

A Discord account would be easier for us, and thanks for your interest!

**Comment by Stieno3000** [comment]
> > dont have discord, should i make a account real quick or do you have reddit or something we can talk on?
> 
> A Discord account would be easier for us, and thanks for your interest!

il comment when i get a account, a bit cramp on time rn due

**Comment by Stieno3000** [comment]
its this: Stieno3000#2111
