### ISSUE TITLE
Why can't the burner give charcoal

### ISSUE THREAD

**Issue by k3vin0210** [Aeyama-Mod/aeyama#130]
**Mod Build:** *163*
**Game Build:** *145*

---

**Issue:** *the burner cant produce charcoal*

**Screenshots:** 
![Screenshot 2023-06-21 5 35 04 PM](https://github.com/Aeyama-Mod/aeyama/assets/135668916/a9d044ea-c3d7-447a-8d3c-249beea42530)

**Comment by k3vin0210** [comment]
(being edited)

**Comment by k3vin0210** [comment]
(done)

**Comment by FredyJabe** [comment]
Not an issue, carbon item being reworked.

**Comment by k3vin0210** [comment]
ok
