### ISSUE TITLE
*(suggestion)*

### ISSUE THREAD

**Issue by k3vin0210** [Aeyama-Mod/aeyama#133]
### Mod Build

*163*

### Game Build

*145.1*

### Issue Description

*(to get charcoal)insert dry wood in a burner to make charcoal (still makes heat) so it wont effect certain setups that use normal wood.*

### Steps to Reproduce

1 insert dry wood
2 wait 5-10 seconds
3 have charcoal produced

**Comment by SunkyMP3G** [comment]
They don't want for burner to provide charcoal **_and_** heat, also they don't have a suggestion form

**Comment by k3vin0210** [comment]
ok

**Comment by JojoFR1** [comment]
First, charcoal doesn't exist (except if you talk about Carbon).
And, if you talk about Carbon, will be available later
