### ISSUE TITLE
loadout schematic don have no core tile

### ISSUE THREAD

**Issue by kapzduke** [Aeyama-Mod/aeyama#139]
### Mod Build

0.4-dev.8

### Game Build

24231

### Issue Description

[crash-report-07_29_2023_00_32_43.txt](https://github.com/Aeyama-Mod/aeyama/files/12198632/crash-report-07_29_2023_00_32_43.txt)

### Steps to Reproduce

use sector generate with aayama

**Comment by RouterXdd** [comment]
Aeyama's planet generator is not supposed to be used. He just a placeholder

**Comment by kapzduke** [comment]
still playable
