### ISSUE TITLE
French Translation : mur large en briques de pierre

### ISSUE THREAD

**Issue by Futuray-pgm** [Aeyama-Mod/aeyama#146]
### Mod Build

0.4-beta.1

### Game Build

145.1

### Issue Description

The French translation of `large stone brick wall` (`block.aeyama-wall-stone-brick-large.name`) is currently `Mur Large en Briques de Pierre`, but for the others large wall, itvs `Grand Mur`.
Does it must to be translated in `Grand Mur en Briques` ?

### Steps to Reproduce

Symply change it in [bundle_fr.properties](https://github.com/Aeyama-Mod/aeyama/blob/main/src/assets/bundles/bundle_fr.properties).

**Comment by JojoFR1** [comment]
It's correct, I made a mistake for the translation, and will fix it later. Thanks for the report I didn't notice.
