### ISSUE TITLE
Unknown Resource

### ISSUE THREAD

**Issue by justintimetodosmth** [Aeyama-Mod/aeyama#149]
### Mod Build

0.3.1

### Game Build

release build 146

### Issue Description

There is an unknown resource in the tech tree... Even though I have already gotten a cheat mode to uncover the resource, it still didn't work.

### Steps to Reproduce

1. Complete the mod (by just finishing the sector)
2. You can download a cheat mod (The one I used is CheatMOD [link: https://github.com/paulieg626/cheat ]) 
3. Use the "Filler" block and place it down. (This will unlock all the resources.)
4. Go to the Tech Tree, then go to resources stuff.
5. You will see that there is still a locked resource, and when you check in the core database, you will see that you already unlocked all the resources.

### Screenshots

![image](https://github.com/Aeyama-Mod/aeyama/assets/147149265/2aa27d72-5411-4730-9dca-4dacc0522eff)

**Comment by justintimetodosmth** [comment]
Also there is 2 sands `sand` and `aeyama-sand` is this intentional?

**Comment by justintimetodosmth** [comment]
`aeyama` is unknowingly a resource.... But it doesn't show up in the core database.

**Comment by justintimetodosmth** [comment]
`survival.msav` is corrupted.... idk why
![image](https://github.com/Aeyama-Mod/aeyama/assets/147149265/70c5d452-b7ce-436d-b8ba-fafa0c96013a)

**Comment by JojoFR1** [comment]
It's water which is unobtainable at the moment.

**Comment by justintimetodosmth** [comment]
> It's water which is unobtainable at the moment.

Oh I thought it was on a different section and why there is two waters

**Comment by JojoFR1** [comment]
We created a copy of the sand and water when we weren't in Java (so can't use vanilla easily). Might change this
