### ISSUE TITLE
Not playable

### ISSUE THREAD

**Issue by Sitemusic81** [Aeyama-Mod/aeyama#156]
### Mod Build

I couldn't find it

### Game Build

146

### Issue Description

After you unlock everything to get to the core frontier you just cant build it because a. It wont let you b. The material limit is 500 and you need 600 bricks

### Steps to Reproduce

Get to frontier
O wait, you cant build frontier because their isnt 2x2 core tiles
O wait you need 600 bricks but the limit is 500 of an item

**Comment by Sitemusic81** [comment]
I've also tried every 2x2 placement possible but it no work, maybe try adding core tiles and redesigning the tiles to look like the floor

**Comment by SunkyMP3G** [comment]
Build storage blocks next to the core to increase item capacity

**Comment by Sitemusic81** [comment]
It's still not fixed

**Comment by Sitemusic81** [comment]
> Build storage blocks next to the core to increase item capacity

It's not that, the core won't even allow me to place it
