### ISSUE TITLE
Sector: [2] Encounter (14)

### ISSUE THREAD

**Issue by FredyJabe** [Aeyama-Mod/aeyama#27]
Defense Sector
You build a ground scanner that annoys the insects, they send scouts toward you, you kill them easily
The scanner detects copper and zinc in the area, you have to find it and harvest some
Unlock ammo
Survive a couple waves

### TODO
- [x] Map
- [x] Research
- [x] Objectives
- [x] Objectives Bundle

**Comment by SunkyMP3G** [comment]
### And
- [ ] Launch cost

**Comment by JojoFR1** [comment]
Update 30/06/2023 - Started working on Objectives (finally).
